file_uploader/urls.py
from django.urls import path

from .views import UploadView

app_name = 'file_uploader'
urlpatterns = [
    path('upload', UploadView.as_view(), name='upload'),
]

savefor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('file_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import LoginUserView, LogoutUserView, PasswordChangeUserView, RegisterUserView
from .forms import UserLoginForm

app_name = 'users'
urlpatterns = [
    path('login', LoginUserView.as_view(authentication_form=UserLoginForm), name='login'),
    path('logout', LogoutUserView.as_view(), name='logout'),
    path('password_change', PasswordChangeUserView.as_view(success_url='login'), name='password_change'),
    path('register', RegisterUserView.as_view(), name='register'),
]

file_uploader/models.py
from django.db import models
from django.contrib.auth import get_user_model


class File(models.Model):
    author = models.ForeignKey(get_user_model(), related_name='files', null=False, on_delete=models.CASCADE)
    file = models.FileField(upload_to='%Y/%m/%d')

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
    """Created only for future changes"""
    use_in_migrations = True

    def _create_user(self, username, password, **extra_fields):
        if not username:
            raise ValueError('Username is required')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', True)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')

        return self._create_user(username, password, **extra_fields)


class User(AbstractUser):
    """Created only for future changes"""
    def __str__(self):
        return self.email

    objects = UserManager()

file_uploader/forms.py
from django import forms


class FileForm(forms.Form):
    file = forms.FileField(label='', widget=forms.FileInput(attrs={'class': 'none'}))

users/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm
from django.utils.translation import gettext as _


class CustomPasswordChangeForm(PasswordChangeForm):
    # Overriden to get rid of help text and change the classes
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'Old password', 'autocomplete': 'current-password', 'autofocus': True}),
    )
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'New password', 'autocomplete': 'new-password'}),
        strip=False,
        help_text=None,
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'New password confirmation', 'autocomplete': 'new-password'}),
    )


class CustomUserCreationForm(UserCreationForm):

    error_messages = {
        'password_too_short': 'The password must contain at least %(min_length)d character.'
    }

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': '',
            'email': ''
        }
        help_texts = {
            'username': None
        }
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'Username'}
            ),
            'email': forms.TextInput(
                attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'Email'}
            )
        }

    password1 = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password',
                   'class': 'l-margin-bottom-1em c-form-box',
                   'placeholder': 'Password'}),
    )
    password2 = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password',
                   'class': 'l-margin-bottom-1em c-form-box',
                   'placeholder': 'Password confirmation'}),
        strip=False,
    )


class UserLoginForm(AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(label='', widget=forms.TextInput(attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'Username'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'class': 'l-margin-bottom-1em c-form-box', 'placeholder': 'Password'}))

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password."
        ),
        'inactive': _("This account is inactive."),
    }

file_uploader/views.py
from django.shortcuts import render
from django.views import View
from django.core.exceptions import PermissionDenied

from .models import File
from .forms import FileForm


class UploadView(View):

    def post(self, request):
        if request.user.is_authenticated is not True:
            raise PermissionDenied()
        context = {}
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            new_file = File(file=request.FILES['file'])
            new_file.author = request.user
            new_file.save()
            context['message'] = 'File uploaded successfully!'
        form = FileForm()
        context['form'] = form
        return render(request, 'file_uploader/upload.html', context)

    def get(self, request):
        if request.user.is_authenticated is not True:
            raise PermissionDenied()
        form = FileForm()
        context = {'form': form}
        return render(request, 'file_uploader/upload.html', context)

users/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm, CustomPasswordChangeForm


class LoginUserView(LoginView):
    template_name = 'users/login.html'


class LogoutUserView(LoginRequiredMixin, LogoutView):
    template_name = 'users/logout.html'


class PasswordChangeUserView(PasswordChangeView):
    template_name = 'users/password_change.html'
    form_class = CustomPasswordChangeForm


class RegisterUserView(CreateView):
    template_name = 'users/register.html'
    model = get_user_model()
    success_url = reverse_lazy('users:login')
    form_class = CustomUserCreationForm

templates/file_uploader/upload.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="GilsonGindreJr">

    <link rel="stylesheet" href="{% static 'css/base/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout/l-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-messages.css' %}">
    <link rel="stylesheet" href="{% static 'css/state/s-state.css' %}">

    <title>Savefor - Upload</title>
</head>
<body>
    <main class="main l-center-h-v">
        <div class="c-background-image"></div>
        <div class="content l-upload-min-height">
            <header class="l-center-h-v l-flex-column">
                <h1 class="c-title-header">Savefor</h1>
                <p class="l-page-title">Upload</p>
            </header>
            {% if message %}
                <div class="l-height-2em l-margin-bottom-1em l-center-h-v c-message-green">
                    {{ message }}
                </div>
            {% endif %}
            <main class="l-content-form">
                <form class="l-center-h l-flex-column" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    <div class="l-height-2em l-flex-row l-margin-bottom-1em">
                        <label for="id_file" class="l-width-49pc l-center-h-v l-margin-right-2pc c-button-grey">Select file</label>
                        <input type="submit" class="l-width-49pc c-button-blue" value="Send file">
                    </div>

                    {{ form }}

                    <span id="file-name" class="l-height-2em l-margin-bottom-1em l-center-h-v c-message-inherit"></span>

                    <div class="l-height-2em l-flex-row l-margin-bottom-1em">
                        <a class="l-width-49pc l-center-h-v l-margin-right-2pc c-a-button c-button-red" href="{% url 'users:logout' %}">Logout</a>
                        <a class="l-width-49pc l-center-h-v c-a-button c-button-grey" href="{% url 'users:password_change' %}">Change Password</a>
                    </div>

                </form>
            </main>
        </div>
    </main>

    <script src="{% static 'js/file-name.js' %}"></script>
</body>
</html>

templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="GilsonGindreJr">

    <link rel="stylesheet" href="{% static 'css/base/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout/l-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-messages.css' %}">


    <title>Savefor - Login</title>
</head>
<body>
    <main class="main l-center-h-v">
        <div class="c-background-image"></div>
        <div class="content">
            <header class="l-center-h-v l-flex-column">
                <h1 class="c-title-header">Savefor</h1>
                <p class="l-page-title">Login</p>
            </header>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="l-height-2em l-margin-bottom-1em l-center-h-v c-message-red">
                        {{ error }}
                    </div>
                {% endfor%}
            {% endif %}
            <main class="l-content-form">
                <form class="c-form l-center-h l-flex-column" method="post">
                    {% csrf_token %}
                    {{ form.username }}
                    {{ form.password }}

                    <div class="l-height-2em l-flex-row l-margin-bottom-1em">
                        <input class="l-width-49pc l-margin-right-2pc c-form-submit c-button-blue" type="submit" value="Login">
                        <a class="l-width-49pc l-center-h-v c-a-button c-button-grey" href="{% url 'users:register' %}">Register</a>
                    </div>
                </form>
            <a class="c-a-link" href="{% url 'users:password_change' %}">Forgot password?</a>
            </main>
        </div>
    </main>
</body>
</html>

templates/users/password_change.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="GilsonGindreJr">

    <link rel="stylesheet" href="{% static 'css/base/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout/l-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-messages.css' %}">


    <title>Savefor - Change Password</title>
</head>
<body>
    <main class="main l-center-h-v">
        <div class="c-background-image"></div>
        <div class="content">
            <header class="l-center-h-v l-flex-column">
                <h1 class="c-title-header">Savefor</h1>
                <p class="l-page-title">Change Password</p>
            </header>
             {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="l-height-2em l-margin-bottom-1em l-center-h-v c-message-red">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor%}
            {% endif %}
            <main class="l-content-form">
                <form class="c-form l-center-h l-flex-column" method="post">
                    {% csrf_token %}
                    {{ form.old_password }}
                    {{ form.new_password1 }}
                    {{ form.new_password2 }}

                    <div class="l-height-2em l-flex-row l-margin-bottom-1em">
                        <input class="l-width-49pc l-margin-right-2pc c-form-submit c-button-blue" type="submit" value="Change password">
                        {% if user.is_authenticated %}
                            <a class="l-width-49pc l-center-h-v c-a-button c-button-grey" href="{% url 'file_uploader:upload' %}">Back</a>
                        {% else %}
                            <a class="l-width-49pc l-center-h-v c-a-button c-button-grey" href="{% url 'users:login' %}">Back</a>
                        {% endif %}
                    </div>
                </form>
            </main>
        </div>
    </main>
</body>
</html>

templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="GilsonGindreJr">

    <link rel="stylesheet" href="{% static 'css/base/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout/l-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-content.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/c-messages.css' %}">


    <title>Savefor - Register</title>
</head>
<body>
    <main class="main l-center-h-v">
        <div class="c-background-image"></div>
        <div class="content">
            <header class="l-center-h-v l-flex-column">
                <h1 class="c-title-header">Savefor</h1>
                <p class="l-page-title">Register</p>
            </header>
             {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="l-height-2em l-margin-bottom-1em l-center-h-v c-message-red">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor%}
            {% endif %}
            <main class="l-content-form">
                <form class="c-form l-center-h l-flex-column" method="post">
                    {% csrf_token %}
                    {{ form.username }}
                    {{ form.email }}
                    {{ form.password1 }}
                    {{ form.password2 }}

                    <div class="l-height-2em l-flex-row l-margin-bottom-1em">
                        <input class="l-width-49pc l-margin-right-2pc c-form-submit c-button-blue" type="submit" value="Register">
                        <a class="l-width-49pc l-center-h-v c-a-button c-button-grey" href="{% url 'users:login' %}">Login</a>
                    </div>
                </form>
            <a class="c-a-link" href="{% url 'users:password_change' %}">Forgot password?</a>
            </main>
        </div>
    </main>
</body>
</html>